myblog/urls.py
from django.contrib import admin
from django.urls import path,re_path

#from blog.views import post_list,post_detail
from blog.views import (
    IndexView,CategoryView,TagView,
    PostDetailView,SearchView,AuthorView
)
from config.views import LinkListView
from .custom_site import custom_site

from comment.views import CommentView

from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.contrib.sitemaps import views as sitemap_views
#class view
urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('category/<str:category_id>/',CategoryView.as_view(),name='category-list'),
    re_path('tag/(?P<tag_id>\d+)/',TagView.as_view(),name='tag-list'),
    re_path('post/(?P<post_id>\d+).html',PostDetailView.as_view(),name='post-detail'),
    path('super_admin/', admin.site.urls,name='super-admin'),
    path('admin/',custom_site.urls,name='admin'),
    path('search/',SearchView.as_view(),name='search'),
    path('author/<str:owner_id>/',AuthorView.as_view(),name='author'),
    path('links/',LinkListView.as_view(),name='links'),
    path('comment/',CommentView.as_view(),name='comment'),
    #rss或feed
    re_path('rss|feed/',LatestPostFeed(),name='rss'),
    re_path('sitemap\.xml',sitemap_views.sitemap,{'sitemaps':{'posts':PostSitemap}}),
]
'''Function View
urlpatterns = [
	path('',post_list),
	path('category/<str:category_id>/',post_list),
	re_path('tag/(?P<tag_id>\d+)/',post_list),
	re_path('post/(?P<post_id>\d+).html',post_detail),
	path('links/',links),
    path('super_admin/', admin.site.urls),
    path('admin/',custom_site.urls),
]'''

'''当前配置的路由可以创建一些路由映射关系：

/admin/
/admin/login/
/admin/logout/
/admin/password_change/
/admin/password_change/done/

/admin/app名称/model名称/
/admin/app名称/model名称/add/
/admin/app名称/model名称/ID值/history/
/admin/app名称/model名称/ID值/change/
/admin/app名称/model名称/ID值/delete/

 '''

comment/models.py
from django.db import models
from blog.models import Post

# Create your models here.
class Comment(models.Model):
	STATUS_NORMAL = 1
	STATUS_DELETE = 0
	STATUS_ITEMS = (
		(STATUS_NORMAL,'正常'),
		(STATUS_DELETE,'删除'),
	)
	target = models.CharField(max_length=100,verbose_name='评论目标')
	content = models.CharField(max_length=2000,verbose_name='内容')
	nickname = models.CharField(max_length=50,verbose_name='昵称')
	website = models.URLField(verbose_name='网站')
	email = models.EmailField(verbose_name='邮箱')
	status = models.PositiveIntegerField(default=STATUS_NORMAL,
		choices=STATUS_ITEMS,verbose_name='状态')
	created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

	class Meta:
		verbose_name = verbose_name_plural = '评论'

	@classmethod
	def get_by_target(cls,target):
		return cls.objects.filter(target=target,status=cls.STATUS_NORMAL)

comment/forms.py
from django import forms

from .models import Comment

import mistune

class CommentForm(forms.ModelForm):
	nickname = forms.CharField(
		label='昵称',
		max_length=50,
		widget=forms.widgets.Input(
			attrs={'class':'form-control','style':"width: 60%;"}
		)
	)
	email = forms.CharField(
		label='Email',
		max_length=50,
		widget=forms.widgets.EmailInput(
			attrs={'class':'form-control','style':"width: 60%;"}
		)
	)
	website = forms.CharField(
		label='网站',
		max_length=100,
		widget=forms.widgets.URLInput(
			attrs={'class':'form-control','style':'width: 60%;'}
		)
	)
	content = forms.CharField(
		label="内容",
		max_length=500,
		widget=forms.widgets.Textarea(
			attrs={'rows':6,'cols':60,'calss':'form-control'}
		)
	)

	def clean_content(self):
		#cleaned_data获取表单数据
		content=self.cleaned_data.get('content')
		if len(content)<10:
			raise forms.ValidationError('Content length is too short!')
		content=mistune.markdown(content)
		return content

	class Meta:
		model = Comment
		fields = ['nickname','email','website','content']

comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from .forms import CommentForm

# Create your views here.
class CommentView(TemplateView):
	http_method_names = ['post']
	template_name = 'comment/result.html'

	def post(self,request,*args,**kwargs):
		comment_form = CommentForm(request.POST)
		target = request.POST.get('target')

		if comment_form.is_valid():
			instance = comment_form.save(commit=False)
			instance.target = target
			instance.save()
			succeed = True
			return redirect(target)
		else:
			succeed = False

		context = {
			'succeed':succeed,
			'form':comment_form,
			'target':target,
		}
		return self.render_to_response(context)

myblog/themes/bootstrap/templates/comment/block.html
<hr>
<div class="comment">
	<form class="form-group" action="/comment/" method="POST">
		{% csrf_token %}
		<input type="hidden" name="target" value="{{target}}">
		{{comment_form}}
		<input type="submit" value="ok">
	</form>

	<ul class="list-group">
		{% for comment in comment_list %}
			<li class="list-group-item">
				<div class="nickname">
					<a href="{{comment.website}}">{{comment.nickname}}</a>
					<span>{{comment.created_time}}</span>
				</div>
				<div class="comment-content">
					<!--关闭自动转码,文本为markdown格式-->
					{% autoescape off %}
						{{comment.content}}
					{% endautoescape %}					
				</div>
			</li>
		{% endfor %}
	</ul>
</div>

myblog/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html>
<head>
	<title>评论结果页</title>
	<style type="text/css">
		body {TEXT_ALIGN:center;}
		.result{
			text-align: center;
			width: 40%;
			margin:auto;
		}
		.errorlist{
			color: red;
		}
		ul li{
			list-style-type: None;
		}
	</style>
</head>
<body>
	<div class="result">
		{% if succeed %}
			<a href="{{target}}">返回</a>
		{% else %}
			<ul class="errorlist">
				{% for field,message in form.errors.items %}
					<li>{{message}}</li>
				{% endfor %}
			</ul>
			<a href="javascript:window.history.back">返回</a>
		{% endif %}
	</div>
</body>
</html>